[versions]
agp = "8.13.0"
kotlin = "2.2.20"
compose-multiplatform = "1.10.0-alpha02"

[libraries]
yalla-resources = { module = "uz.yalla:resources", version = "1.0.0" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = { id = "maven-publish" }
